// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package di

import (
	"github.com/ajordi/todo/pkg/adding"
	gorm2 "github.com/ajordi/todo/pkg/storage/gorm"
	"github.com/jinzhu/gorm"
)

// Injectors from wire.go:

func InitTaskAPI(db *gorm.DB) adding.TaskAPI {
	taskRepository := gorm2.ProvideTaskRepository(db)
	taskService := adding.ProvideTaskService(taskRepository)
	taskAPI := adding.ProvideTaskAPI(taskService)
	return taskAPI
}
